Repository IbisNeuronav/Ibis, pull requests merged in 2020-07, with the labels that each got.

#325 Issue 324 - programmatically hiding/showing objects
  IbisLib/gui/objecttreemodel.cpp
  IbisLib/gui/objecttreemodel.h
  IbisLib/scenemanager.cpp
  IbisLib/scenemanager.h
  IbisLib/sceneobject.cpp
  IbisLib/sceneobject.h
Labels: bug

#346 Fixed OpenFileDialog for Qt5.12 and higher
  IbisLib/gui/opendatafiledialog.cpp
Labels: bug

#347 Pedicle screw navigation plugin
  IbisPlugins/PedicleScrewNavigation/CMakeLists.txt
  IbisPlugins/PedicleScrewNavigation/declare-plugin.cmake
  IbisPlugins/PedicleScrewNavigation/itkWeightRegistration/CMakeLists.txt
  IbisPlugins/PedicleScrewNavigation/itkWeightRegistration/GPUWeightMatchingMatrixTransformationSparseMaskKernel.cl
  IbisPlugins/PedicleScrewNavigation/itkWeightRegistration/gpu_weightrigidregistration.cpp
  IbisPlugins/PedicleScrewNavigation/itkWeightRegistration/gpu_weightrigidregistration.h
  IbisPlugins/PedicleScrewNavigation/itkWeightRegistration/itkGPU3DRigidSimilarityWeightMetric.h
  IbisPlugins/PedicleScrewNavigation/itkWeightRegistration/itkGPUWeightMatchingMatrixTransformationSparseMask.h
  IbisPlugins/PedicleScrewNavigation/itkWeightRegistration/itkGPUWeightMatchingMatrixTransformationSparseMask.hxx
  IbisPlugins/PedicleScrewNavigation/pediclescrewnavigationplugininterface.cpp
  IbisPlugins/PedicleScrewNavigation/pediclescrewnavigationplugininterface.h
  IbisPlugins/PedicleScrewNavigation/screwnavigationwidget.cpp
  IbisPlugins/PedicleScrewNavigation/screwnavigationwidget.h
  IbisPlugins/PedicleScrewNavigation/screwnavigationwidget.ui
  IbisPlugins/PedicleScrewNavigation/screwproperties.cpp
  IbisPlugins/PedicleScrewNavigation/screwproperties.h
  IbisPlugins/PedicleScrewNavigation/screwtablewidget.cpp
  IbisPlugins/PedicleScrewNavigation/screwtablewidget.h
  IbisPlugins/PedicleScrewNavigation/screwtablewidget.ui
  IbisPlugins/PedicleScrewNavigation/vertebraregistrationwidget.cpp
  IbisPlugins/PedicleScrewNavigation/vertebraregistrationwidget.h
  IbisPlugins/PedicleScrewNavigation/vertebraregistrationwidget.ui
Labels: enhancement

#350 Correct spelling in plugin descriptions
  IbisPlugins/FrameRateTester/declare-plugin.cmake
  IbisPlugins/PRISMVolumeRender/declare-plugin.cmake
  IbisPlugins/RecordTracking/declare-plugin.cmake
Labels: Spelling
